### ISSUE TITLE
Add pity timer for Epic and Legendary

### ISSUE THREAD

**Issue by IlyaHalsky** [SpeedoDevo/packr#15]
Subj

**Comment by bashforgo** [comment]
There is already a [pity timer](https://github.com/SpeedoDevo/packr/blob/master/src/app/data/packs-generator.service.ts#L69-L71).

**Comment by IlyaHalsky** [comment]
Oh, just opened 70 packs with 1 legendary. Guess I'm just lucky:)

**Comment by IlyaHalsky** [comment]
Adding dust count for repeated cards would be nice too :)
Oops, I'm retarded.

**Comment by bashforgo** [comment]
That is in the raw stats tab, on the bottom, in the Regular Extra, Golden Extra, and Extras column.

**Comment by IlyaHalsky** [comment]
Is there a way to run average computation, say stats for 100 openings of x70 packs?

**Comment by bashforgo** [comment]
Not yet - but I might implement that in the future, lot of people have been asking for that.

**Comment by IlyaHalsky** [comment]
I guess I will do it old fashion with excel and lots of beer.
Thanks!
